/-!
G7 Adversarial Mobility Confinement: abstract strategy-certificate schema.

This file formalizes the layer-agnostic game/certificate surface from
`THEOREMS.md` for G7. It does not construct the classical angel-problem board,
Chebyshev metric, finite boards, or the Conway/Berlekamp/Mathe/Kloster/
Bowditch/Gacs proofs; those are calibration and lab content.
-/

namespace SixBirdsFoundationsVI.Laws.G7AdversarialMobilityConfinement

/--
A visible game state bundles the agent position and the obstruction/deletion
record.

`Obs` is deliberately abstract: it may be a deleted set, a finite-board state,
or any other visible obstruction record supplied by a concrete game.
-/
structure GameState (Pos Obs : Type) where
  pos : Pos
  obs : Obs

/--
Apply one complete turn: the angel moves to a new position, then the devil
updates the visible obstruction record.
-/
def applyTurn {Pos Obs : Type} (_s : GameState Pos Obs) (p : Pos) (d : Obs) :
    GameState Pos Obs :=
  { pos := p, obs := d }

/--
The angel is stuck at a state when no legal next position exists.
-/
def Stuck {Pos Obs : Type} (legal : GameState Pos Obs → Pos → Prop)
    (s : GameState Pos Obs) : Prop :=
  ¬ ∃ p : Pos, legal s p

/--
`[H-G7-escape-strategy]`: a visible angel strategy with an invariant.

At every invariant state, `sigmaA` proposes a legal move, and every legal
devil response preserves the invariant for the next visible state.
-/
def EscapeStrategy {Pos Obs : Type}
    (legal : GameState Pos Obs → Pos → Prop)
    (devilLegal : GameState Pos Obs → Pos → Obs → Prop)
    (sigmaA : GameState Pos Obs → Pos)
    (I : GameState Pos Obs → Prop) : Prop :=
  ∀ s : GameState Pos Obs, I s →
    legal s (sigmaA s) ∧
      ∀ d : Obs,
        devilLegal s (sigmaA s) d →
          I (applyTurn s (sigmaA s) d)

/--
The play generated by fixed angel and devil strategies from an initial state.
-/
def Play {Pos Obs : Type}
    (sigmaA : GameState Pos Obs → Pos)
    (sigmaD : GameState Pos Obs → Pos → Obs) :
    GameState Pos Obs → Nat → GameState Pos Obs
  | s0, 0 => s0
  | s0, n + 1 =>
      let s := Play sigmaA sigmaD s0 n
      applyTurn s (sigmaA s) (sigmaD s (sigmaA s))

/--
G7 escape theorem: a discharged escape strategy keeps every legal-devil play
inside the invariant and never stuck at any finite turn.
-/
theorem escape_never_stuck {Pos Obs : Type}
    {legal : GameState Pos Obs → Pos → Prop}
    {devilLegal : GameState Pos Obs → Pos → Obs → Prop}
    {sigmaA : GameState Pos Obs → Pos}
    {I : GameState Pos Obs → Prop}
    (hescape : EscapeStrategy legal devilLegal sigmaA I)
    {s0 : GameState Pos Obs} (hI0 : I s0)
    (sigmaD : GameState Pos Obs → Pos → Obs)
    (hdevilLegal : ∀ (s : GameState Pos Obs) (p : Pos),
      legal s p → devilLegal s p (sigmaD s p)) :
    ∀ n : Nat,
      I (Play sigmaA sigmaD s0 n) ∧
        ¬ Stuck legal (Play sigmaA sigmaD s0 n) := by
  intro n
  induction n with
  | zero =>
      have hstep := hescape s0 hI0
      constructor
      · exact hI0
      · intro hstuck
        exact hstuck ⟨sigmaA s0, hstep.left⟩
  | succ n ih =>
      rcases ih with ⟨hI, _hnotStuck⟩
      let s := Play sigmaA sigmaD s0 n
      have hstep := hescape s hI
      have hnextI :
          I (applyTurn s (sigmaA s) (sigmaD s (sigmaA s))) :=
        hstep.right (sigmaD s (sigmaA s))
          (hdevilLegal s (sigmaA s) hstep.left)
      have hnextStep :=
        hescape (applyTurn s (sigmaA s) (sigmaD s (sigmaA s))) hnextI
      constructor
      · simpa [Play, s] using hnextI
      · intro hstuck
        exact hstuck
          ⟨sigmaA (applyTurn s (sigmaA s) (sigmaD s (sigmaA s))),
            hnextStep.left⟩

/--
`[H-G7-confinement-strategy]`: a visible devil strategy with a rank decrease.

For every legal angel move, the devil's prescribed response must itself be a
legal devil update, and that legal update must strictly decrease the supplied
natural-number rank. The legality conjunct rules out an illegal instant-trap
record being accepted merely because it decreases `rank`.
-/
def ConfinementStrategy {Pos Obs : Type}
    (legal : GameState Pos Obs → Pos → Prop)
    (devilLegal : GameState Pos Obs → Pos → Obs → Prop)
    (sigmaD : GameState Pos Obs → Pos → Obs)
    (rank : GameState Pos Obs → Nat) : Prop :=
  ∀ (s : GameState Pos Obs) (p : Pos),
    legal s p →
      devilLegal s p (sigmaD s p) ∧
        rank (applyTurn s p (sigmaD s p)) < rank s

/--
An angel strategy is honest when it proposes a legal move whenever a legal move
exists. A function that proposes illegal moves while legal moves remain is not a
legal angel strategy for the confinement theorem.
-/
def AngelHonest {Pos Obs : Type}
    (legal : GameState Pos Obs → Pos → Prop)
    (sigmaA : GameState Pos Obs → Pos) : Prop :=
  ∀ s : GameState Pos Obs, ¬ Stuck legal s → legal s (sigmaA s)

/--
Peeling the first generated turn from a play.

This converts the recursive "append one turn at the end" definition of `Play`
into the "take the first turn, then continue" shape needed for fuel induction.
-/
theorem play_succ_from_initial {Pos Obs : Type}
    (sigmaA : GameState Pos Obs → Pos)
    (sigmaD : GameState Pos Obs → Pos → Obs) :
    ∀ (s : GameState Pos Obs) (n : Nat),
      Play sigmaA sigmaD s (n + 1) =
        Play sigmaA sigmaD
          (applyTurn s (sigmaA s) (sigmaD s (sigmaA s))) n := by
  intro s n
  induction n with
  | zero =>
      simp [Play]
  | succ n ih =>
      change
        applyTurn (Play sigmaA sigmaD s (n + 1))
            (sigmaA (Play sigmaA sigmaD s (n + 1)))
            (sigmaD (Play sigmaA sigmaD s (n + 1))
              (sigmaA (Play sigmaA sigmaD s (n + 1)))) =
          applyTurn
            (Play sigmaA sigmaD
              (applyTurn s (sigmaA s) (sigmaD s (sigmaA s))) n)
            (sigmaA
              (Play sigmaA sigmaD
                (applyTurn s (sigmaA s) (sigmaD s (sigmaA s))) n))
            (sigmaD
              (Play sigmaA sigmaD
                (applyTurn s (sigmaA s) (sigmaD s (sigmaA s))) n)
              (sigmaA
                (Play sigmaA sigmaD
                  (applyTurn s (sigmaA s) (sigmaD s (sigmaA s))) n)))
      rw [ih]

/--
Fuel-indexed confinement helper: if a state has rank at most `fuel`, then a
honest angel playing against a confinement strategy is stuck within `fuel`
turns.
-/
theorem confinement_forces_trap_with_fuel {Pos Obs : Type}
    {legal : GameState Pos Obs → Pos → Prop}
    {devilLegal : GameState Pos Obs → Pos → Obs → Prop}
    {sigmaA : GameState Pos Obs → Pos}
    {sigmaD : GameState Pos Obs → Pos → Obs}
    {rank : GameState Pos Obs → Nat}
    (hconfine : ConfinementStrategy legal devilLegal sigmaD rank)
    (hhonest : AngelHonest legal sigmaA) :
    ∀ (fuel : Nat) (s : GameState Pos Obs),
      rank s ≤ fuel →
        ∃ n : Nat, n ≤ fuel ∧ Stuck legal (Play sigmaA sigmaD s n) := by
  intro fuel
  induction fuel with
  | zero =>
      intro s hrank
      by_cases hstuck : Stuck legal s
      · exact ⟨0, Nat.zero_le 0, by simpa [Play] using hstuck⟩
      · have hlegal : legal s (sigmaA s) := hhonest s hstuck
        have hrankZero : rank s = 0 := Nat.eq_zero_of_le_zero hrank
        have hdecrease :
            rank (applyTurn s (sigmaA s) (sigmaD s (sigmaA s))) < rank s :=
          (hconfine s (sigmaA s) hlegal).2
        rw [hrankZero] at hdecrease
        exact False.elim (Nat.not_lt_zero _ hdecrease)
  | succ fuel ih =>
      intro s hrank
      by_cases hstuck : Stuck legal s
      · exact ⟨0, Nat.zero_le (fuel + 1), by simpa [Play] using hstuck⟩
      · have hlegal : legal s (sigmaA s) := hhonest s hstuck
        let s1 := applyTurn s (sigmaA s) (sigmaD s (sigmaA s))
        have hdecrease : rank s1 < rank s :=
          (hconfine s (sigmaA s) hlegal).2
        have hs1LeFuel : rank s1 ≤ fuel :=
          Nat.le_of_lt_succ (Nat.lt_of_lt_of_le hdecrease hrank)
        rcases ih s1 hs1LeFuel with ⟨n, hnLe, hnStuck⟩
        refine ⟨n + 1, Nat.succ_le_succ hnLe, ?_⟩
        rw [play_succ_from_initial sigmaA sigmaD s n]
        exact hnStuck

/--
G7 confinement theorem: a discharged confinement strategy traps every honest
angel strategy after finitely many turns, bounded by the initial rank.
-/
theorem confinement_forces_trap {Pos Obs : Type}
    {legal : GameState Pos Obs → Pos → Prop}
    {devilLegal : GameState Pos Obs → Pos → Obs → Prop}
    {sigmaA : GameState Pos Obs → Pos}
    {sigmaD : GameState Pos Obs → Pos → Obs}
    {rank : GameState Pos Obs → Nat}
    (hconfine : ConfinementStrategy legal devilLegal sigmaD rank)
    (hhonest : AngelHonest legal sigmaA) :
    ∀ s0 : GameState Pos Obs,
      ∃ n : Nat, n ≤ rank s0 ∧ Stuck legal (Play sigmaA sigmaD s0 n) := by
  intro s0
  exact confinement_forces_trap_with_fuel hconfine hhonest (rank s0) s0
    (Nat.le_refl (rank s0))

/--
No natural-number-valued sequence can strictly decrease forever.

The proof is elementary and local: first show by induction that
`f n + n <= f 0`, then instantiate at `n = f 0 + 1`.
-/
theorem no_infinite_nat_descent (f : Nat → Nat)
    (hdecrease : ∀ n : Nat, f (n + 1) < f n) : False := by
  have hbound : ∀ n : Nat, f n + n ≤ f 0 := by
    intro n
    induction n with
    | zero =>
        simp
    | succ n ih =>
        have hstep : f (n + 1) + 1 ≤ f n := Nat.succ_le_of_lt (hdecrease n)
        have hstepAdd : (f (n + 1) + 1) + n ≤ f n + n :=
          Nat.add_le_add_right hstep n
        have hcurrent : f (n + 1) + (n + 1) ≤ f n + n := by
          simpa [Nat.add_assoc, Nat.add_comm, Nat.add_left_comm] using hstepAdd
        exact Nat.le_trans hcurrent ih
  let n := f 0 + 1
  have htooLarge : n ≤ f n + n := Nat.le_add_left n (f n)
  have hbad : n ≤ f 0 := Nat.le_trans htooLarge (hbound n)
  exact Nat.lt_irrefl (f 0) (Nat.lt_of_succ_le hbad)

/--
Escape and confinement certificates are mutually exclusive for one fixed game.

If both were valid, run the escaping angel strategy against the confining
devil strategy. Escape supplies a legal angel move at every finite turn, while
confinement makes the natural rank strictly decrease at every turn, impossible
by `no_infinite_nat_descent`.
-/
theorem escape_confinement_mutually_exclusive {Pos Obs : Type}
    {legal : GameState Pos Obs → Pos → Prop}
    {devilLegal : GameState Pos Obs → Pos → Obs → Prop}
    {sigmaA : GameState Pos Obs → Pos}
    {sigmaD : GameState Pos Obs → Pos → Obs}
    {I : GameState Pos Obs → Prop}
    {rank : GameState Pos Obs → Nat}
    (hescape : EscapeStrategy legal devilLegal sigmaA I)
    (hconfine : ConfinementStrategy legal devilLegal sigmaD rank)
    (hdevilLegal : ∀ (s : GameState Pos Obs) (p : Pos),
      legal s p → devilLegal s p (sigmaD s p))
    {s0 : GameState Pos Obs} (hI0 : I s0) : False := by
  let f : Nat → Nat := fun n => rank (Play sigmaA sigmaD s0 n)
  have hsurvive :
      ∀ n : Nat,
        I (Play sigmaA sigmaD s0 n) ∧
          ¬ Stuck legal (Play sigmaA sigmaD s0 n) :=
    escape_never_stuck hescape hI0 sigmaD hdevilLegal
  have hdecrease : ∀ n : Nat, f (n + 1) < f n := by
    intro n
    let s := Play sigmaA sigmaD s0 n
    have hI : I s := (hsurvive n).left
    have hlegal : legal s (sigmaA s) := (hescape s hI).left
    simpa [f, s, Play] using (hconfine s (sigmaA s) hlegal).2
  exact no_infinite_nat_descent f hdecrease

end SixBirdsFoundationsVI.Laws.G7AdversarialMobilityConfinement
