from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from .canonical import canonical_bytes, load_json, sha256_value, write_json
from .evaluator import evaluate
from .fixtures import FIXTURE_ROOT, load_countermodels, load_scenarios


def evaluate_all() -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    scenarios = load_scenarios()
    scenario_raw = {s.fixture_id: load_json(s.source_path) for s in scenarios}
    scenario_results: list[dict[str, Any]] = []
    observed_by: dict[str, str] = {}
    for scenario in scenarios:
        observed_status, facts = evaluate(scenario.flags)
        derived = facts.as_mapping()
        assertion_results = {
            key: derived.get(key) == expected
            for key, expected in sorted(scenario.assertions.items())
        }
        core = {
            "fixture_id": scenario.fixture_id,
            "expected_status": scenario.expected_status,
            "observed_status": observed_status,
            "status_pass": observed_status == scenario.expected_status,
            "assertion_results": assertion_results,
            "all_pass": observed_status == scenario.expected_status
            and all(assertion_results.values()),
            "derived": derived,
            "canonical_input_sha256": sha256_value(scenario_raw[scenario.fixture_id]),
        }
        core["canonical_result_sha256"] = sha256_value(core)
        scenario_results.append(core)
        observed_by[scenario.fixture_id] = observed_status

    countermodel_results: list[dict[str, Any]] = []
    for countermodel in load_countermodels():
        actual_scenario_hash = sha256_value(scenario_raw[countermodel.scenario_id])
        result = {
            "fixture_id": countermodel.fixture_id,
            "scenario_id": countermodel.scenario_id,
            "expected_status": countermodel.expected_status,
            "observed_status": observed_by[countermodel.scenario_id],
            "scenario_hash_pass": actual_scenario_hash == countermodel.scenario_sha256,
            "status_pass": observed_by[countermodel.scenario_id]
            == countermodel.expected_status,
        }
        result["all_pass"] = result["scenario_hash_pass"] and result["status_pass"]
        result["canonical_result_sha256"] = sha256_value(result)
        countermodel_results.append(result)
    return scenario_results, countermodel_results


def write_results(result_root: Path) -> dict[str, Any]:
    scenario_results, countermodel_results = evaluate_all()
    scenario_path = result_root / "python_scenario_results.jsonl"
    countermodel_path = result_root / "python_countermodel_results.jsonl"
    result_root.mkdir(parents=True, exist_ok=True)
    scenario_path.write_bytes(b"".join(canonical_bytes(x) for x in scenario_results))
    countermodel_path.write_bytes(b"".join(canonical_bytes(x) for x in countermodel_results))
    summary = {
        "implementation": "python-standard-library-independent-evaluator",
        "scenario_count": len(scenario_results),
        "scenario_pass_count": sum(x["all_pass"] for x in scenario_results),
        "countermodel_count": len(countermodel_results),
        "countermodel_pass_count": sum(x["all_pass"] for x in countermodel_results),
        "all_pass": all(x["all_pass"] for x in scenario_results + countermodel_results),
        "scenario_results_sha256": __import__("hashlib").sha256(
            scenario_path.read_bytes()
        ).hexdigest(),
        "countermodel_results_sha256": __import__("hashlib").sha256(
            countermodel_path.read_bytes()
        ).hexdigest(),
    }
    write_json(result_root / "python_summary.json", summary)
    return summary


def compare_with_lean(lean_results: Path, output: Path) -> dict[str, Any]:
    """Compare extracted Lean results with Python without trusting either side.

    The Lean result file is generated by executing `#eval` in the compiled Lean
    project.  Static expectation files are never accepted as Lean execution.
    """
    scenario_results, countermodel_results = evaluate_all()
    python_rows = {
        row["fixture_id"]: (row["observed_status"], row["all_pass"])
        for row in scenario_results + countermodel_results
    }
    lean_rows: dict[str, tuple[str, bool]] = {}
    for line in lean_results.read_text(encoding="utf-8").splitlines():
        if not line.strip():
            continue
        row = json.loads(line)
        lean_rows[row["fixture_id"]] = (row["observed_status"], row["all_pass"])
    shared = sorted(set(python_rows) & set(lean_rows))
    mismatches = [
        {"fixture_id": fixture_id, "python": python_rows[fixture_id], "lean": lean_rows[fixture_id]}
        for fixture_id in shared
        if python_rows[fixture_id] != lean_rows[fixture_id]
    ]
    report = {
        "python_count": len(python_rows),
        "lean_count": len(lean_rows),
        "shared_count": len(shared),
        "missing_from_lean": sorted(set(python_rows) - set(lean_rows)),
        "missing_from_python": sorted(set(lean_rows) - set(python_rows)),
        "mismatches": mismatches,
        "all_pass": len(shared) == len(python_rows) == len(lean_rows) and not mismatches,
    }
    write_json(output, report)
    return report
