"""Exact-Fraction Xi substrate ported from the reviewed Lean files."""

from .adequacy_residual import (
    adequacyResidual,
    blockCurrencyDD,
    blockCurrencyDL,
    blockCurrencyLD,
    blockCurrencyLL,
)
from .critical_pair import (
    conditionalCurrencyDM_L,
    conditionalCurrencyMD_L,
    conditionalCurrencyMM_L,
)
from .currency import xiCurrency, xiMinimumSpendCost
from .matrix import (
    ExtendedRat,
    InRange,
    Mat,
    PositiveSemidefinite,
    ScalarInput,
    StrictPositiveDiagonal,
    Symmetric,
    Vec,
    diagonalPseudoInverse,
    dot,
    identityMat,
    mat,
    matAdd,
    matMul,
    matScale,
    matSub,
    matVec,
    quad,
    shape,
    standardBasis,
    traceMat,
    transpose,
    vec,
    zeroMat,
)
from .strict_extension import is_same_family_saturated, loewnerLE

__all__ = [
    "ExtendedRat",
    "InRange",
    "Mat",
    "PositiveSemidefinite",
    "ScalarInput",
    "StrictPositiveDiagonal",
    "Symmetric",
    "Vec",
    "adequacyResidual",
    "blockCurrencyDD",
    "blockCurrencyDL",
    "blockCurrencyLD",
    "blockCurrencyLL",
    "conditionalCurrencyDM_L",
    "conditionalCurrencyMD_L",
    "conditionalCurrencyMM_L",
    "diagonalPseudoInverse",
    "dot",
    "identityMat",
    "is_same_family_saturated",
    "loewnerLE",
    "mat",
    "matAdd",
    "matMul",
    "matScale",
    "matSub",
    "matVec",
    "quad",
    "shape",
    "standardBasis",
    "traceMat",
    "transpose",
    "vec",
    "xiCurrency",
    "xiMinimumSpendCost",
    "zeroMat",
]
