#!/usr/bin/env python3
"""Build Step-1 canonical role, glossary, alias, and correction registries."""
from __future__ import annotations
import csv, json
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
REG=ROOT/'registry'; SYN=ROOT/'synthesis'; DEC=ROOT/'decisions'
for d in (REG,SYN,DEC): d.mkdir(parents=True,exist_ok=True)

roles=[
 dict(role_id='P1',canonical_name='Descent compatibility / obstruction',canonical_meaning='Compatibility of an update or transport with a quotient; when compatibility fails, the role records the obstruction to descent.',behavioral='Descent succeeds or fails for the declared update/readout.',verification='A descended-map proof or an explicit split-pair/no-map obstruction witness.',structural='Quotient data equipped with a descended map, or quotient/update/readout data carrying an obstruction record.',activation='Requires aligned quotient, update/transport, target readout, threshold data, witness schema, level and audit.',boundary='Generic semantics, interpretation, or mere route data is not P1.',source_paper='P027',source_path='papers/Tsiokos_2026_Six_Birds_Foundations_II_Admissibility_Meta_Theory_and_the_Exact_Six_Program.tex',source_line='268-284; 326-352',source_label='def:primitive-roles; rem:per-primitive-levels'),
 dict(role_id='P2',canonical_name='Macro-specification representability',canonical_meaning='Whether a declared macro specification, constraint, gate, or target is representable/realizable in the current typed setting.',behavioral='Representable or non-representable status.',verification='Representability or non-representability certificate.',structural='A macro-specification layer together with a realization relation.',activation='Requires a genuine specification/realization problem, threshold and witness—not a bare label or arbitrary constraint.',boundary='P2 is not every predicate and not a substitute for P6 accounting.',source_paper='P027',source_path='papers/Tsiokos_2026_Six_Birds_Foundations_II_Admissibility_Meta_Theory_and_the_Exact_Six_Program.tex',source_line='268-284; 326-352',source_label='def:primitive-roles; rem:per-primitive-levels'),
 dict(role_id='P3',canonical_name='Enriched route/coherence mismatch',canonical_meaning='Disagreement, non-reducibility, or holonomy among declared enriched routes or coherence data.',behavioral='Witnessed route disagreement or mismatch.',verification='Generated route terms and a non-reducibility/mismatch certificate.',structural='A categorical route grammar or reduced categorical universe carrying the routes.',activation='Requires two or more admissible routes and a typed comparison; generic transition data is insufficient.',boundary='P3 is diagnostic route structure, not a directionality certificate; P6_drive is separately required.',source_paper='P027',source_path='papers/Tsiokos_2026_Six_Birds_Foundations_II_Admissibility_Meta_Theory_and_the_Exact_Six_Program.tex',source_line='268-303; 326-352',source_label='def:primitive-roles; rem:repaired-alignments; rem:p6-drive'),
 dict(role_id='P4',canonical_name='Stage / order / transition / refinement structure',canonical_meaning='Typed architecture of stages, order, transitions, refinements, sectors, or gluing relations.',behavioral='Stage status, transition occurrence, or refinement behavior.',verification='Order/preorder, transition, or refinement certificate.',structural='A stage/refinement architecture with nontrivial laws.',activation='Requires non-identity ordered/refinement structure and its laws; arbitrary relations or labels do not activate P4.',boundary='P4 records organization of change; it does not by itself certify novelty, closure, or directionality.',source_paper='P027',source_path='papers/Tsiokos_2026_Six_Birds_Foundations_II_Admissibility_Meta_Theory_and_the_Exact_Six_Program.tex',source_line='268-284; 326-352; 1587-1608',source_label='def:primitive-roles; prop:p4-witness'),
 dict(role_id='P5',canonical_name='Quotient packaging / quotienting',canonical_meaning='Identification of distinctions into a quotient/package together with validity or universal-property data.',behavioral='Packaging or identification behavior.',verification='Equivalence and quotient-validity certificate.',structural='A quotient object, packaging map, and universal-property or tower/coarsening data.',activation='Requires distinct raw objects, a nontrivial equivalence/identification, a packaging map, and quotient-validity evidence.',boundary='Generic paths or derivations are not P5; strictness and closure are separate predicates on a package/bridge.',source_paper='P027',source_path='papers/Tsiokos_2026_Six_Birds_Foundations_II_Admissibility_Meta_Theory_and_the_Exact_Six_Program.tex',source_line='268-293; 326-352; 1610-1631',source_label='def:primitive-roles; prop:p5-witness'),
 dict(role_id='P6',canonical_name='Audit / bookkeeping / provenance / replay / checkability',canonical_meaning='Typed records that make claims, events, sources, dependencies, costs, replay, and checks interrogable.',behavioral='Audit-relevant event occurrence or record–event association.',verification='A checkable audit record.',structural='An audit schema carrying provenance, replay, dependency, and check relations.',activation='Requires event-reference, source/dependency, and replay/check structure; passive logs or partial records are insufficient.',boundary='P6 is broader than directionality. P6_drive is a narrow affinity-carrying, detailed-balance-breaking face.',source_paper='P027',source_path='papers/Tsiokos_2026_Six_Birds_Foundations_II_Admissibility_Meta_Theory_and_the_Exact_Six_Program.tex',source_line='268-303; 326-352; 1633-1653',source_label='def:primitive-roles; rem:p6-drive; prop:p6-witness'),
]
fields=list(roles[0])
with (REG/'primitive_roles.csv').open('w',newline='',encoding='utf-8') as f:
 w=csv.DictWriter(f,fieldnames=fields); w.writeheader(); w.writerows(roles)
with (REG/'primitive_roles.jsonl').open('w',encoding='utf-8') as f:
 for r in roles: f.write(json.dumps(r,ensure_ascii=False)+'\n')
md=['# Canonical primitive-role registry','',
    'Authority: Foundations II controls the preferred meanings. Foundations I’s older operational labels are retained as historical realizations, not competing definitions.','']
for r in roles:
 md += [f"## {r['role_id']} — {r['canonical_name']}",'',r['canonical_meaning'],'',f"- **Behavioral:** {r['behavioral']}",f"- **Verification:** {r['verification']}",f"- **Structural-categorical:** {r['structural']}",f"- **Activation:** {r['activation']}",f"- **Non-collapse boundary:** {r['boundary']}",f"- **Source:** {r['source_paper']} `{r['source_path']}` lines {r['source_line']} (`{r['source_label']}`).",'']
(REG/'primitive_roles.md').write_text('\n'.join(md),encoding='utf-8')

terms=[
('theory package','canonical','A typed package `(Z, f, Σ_f, E, A)` comprising carrier, declared lens, induced definability structure, packaging/completion endomap, and audit. Variants may add dynamics or records but must not silently replace these fields.','P030','302-312','def:theory-package','package; closure package','A theory package is not merely a model description; formation claims require fixed-point and audit records.'),
('carrier','canonical','The underlying finite state/content domain `Z` on which the package is defined.','P030','302-312','def:theory-package','substrate; state space','Carrier identity, theory identity, and layer identity are distinct.'),
('lens','canonical','A declared map/interface `f` specifying what distinctions are available to the package.','P030','302-312','def:theory-package','readout; coarse graining; interface','A lens may be partial in future VII work, but the existing canonical package does not by itself supply a partial-domain calculus.'),
('definability structure','canonical','`Σ_f`, the family/algebra of distinctions expressible through the declared lens.','P030','302-312','def:theory-package','definability algebra; observable algebra','Definability is lens-relative; hidden carrier distinctions are not automatically layer facts.'),
('completion / packaging endomap','canonical','The endomap `E` whose fixed points supply packaged candidates and whose idempotence/defect is audited.','P031','460-590','def:closed-points; def:D-IC-02','completion; packaging operator','Iterating one fixed idempotent does not generate an open-ended ladder.'),
('audit','canonical','The record/check functional `A` and surrounding provenance discipline under which a package or claim is accepted.','P027','671-920','def:audited; def:admissible-claim','bookkeeping; ledger; provenance','Audit is constitutive of admissibility, but SBT is not reducible to audit.'),
('formed object','canonical','A declared fixed point of completion with its associated formation, record, and audit conditions included in the package.','P030','302-312','def:theory-package','object; packaged object','Fixed-point syntax alone is not sufficient when formation records or audits are absent.'),
('objecthood / stability certificate','canonical synthesis','Evidence that a candidate survives the declared packaging/completion operation, exactly or within a declared defect tolerance.','P031','359-590','def:closure-operator; def:closed-points; def:D-IC-02','closure certificate','Objecthood is separate from novelty and directionality.'),
('strict extension / novelty certificate','canonical','A refinement/new package retains the lower readout and separates at least one lower-indistinguishable pair; equivalently, the new readout does not factor through the old.','P028','1963','lem:F8','strictness; nonfactorization','Strictness alone does not imply closure, promotion acceptance, endogeny, or drive.'),
('directionality certificate','canonical synthesis','An accepted P6-side audit of time-reversal asymmetry or non-exact affinity that survives the declared observation/protocol conditions.','P031','710-920','arrow/affinity section','arrow; drive','Route mismatch or holonomy alone is not directionality.'),
('P6_drive','canonical specialization','The affinity-carrying, detailed-balance-breaking face of P6 used for honest directionality claims.','P027','295-303','rem:p6-drive','drive face','It is a specialization of P6, not a seventh role and not a replacement for general audit.'),
('closure ladder','canonical','An ordered sequence of closures/packages in which later stages are strictly stronger; open-endedness requires changing or enlarging operators/interfaces rather than repeated application of one idempotent.','P031','393-450','def:closure-ladder','layer ladder','Finite fixed interfaces have bounded definability and cannot support an infinite strict ladder.'),
('level trichotomy','canonical','Behavioral status, verification/certificate, and structural-categorical support are three lossy levels for each primitive role.','P027','305-352','def:level-trichotomy','behavioral/verification/structural levels','Lifts upward require added data and are selected, not unique.'),
('FATCD','canonical scoped domain','The finite audited typed closure-description domain over which Foundations II proves its scoped exact-six theorem.','P027','1030-1160','def:fatcd','finite audited typed closure descriptions','Membership does not require all six role projections to be active.'),
('role channel','canonical','One of exactly six typed slots in a decomposition/exhaustion record; a channel may be inactive, below threshold, collapsed, absent-with-record, or out of scope.','P027','1419; 2379','rem:channel-vs-activation-reminder','primitive channel','Channel presence is not role activation.'),
('active role projection','canonical','An honestly supported interpretation of raw features as one P-role, carrying threshold, witness, level, evidence, collapse, loss/lift, and nonclaim data.','P027','1208-1245','def:role-projection','activation','A FATCD description may activate none, some, or all six channels.'),
('scoped exact-six','canonical theorem scope','Within FATCD and an explicit recognition hypothesis, every admissible description has an existential, non-unique decomposition/exhaustion record with six role channels and no required seventh irreducible role in the covered scope.','P027','2715-3030','thm:scoped-exact-six','exact six','Not a universal algebra, uniqueness theorem, empirical realization, or claim that every description activates all six.'),
('BirdInt_fin^aud','canonical calculus','The finite audited typed interaction record/calculus carrying packages, instruments, profiles, witnesses, updates, defects, judgments, statuses, gates, dependencies, audits, visibility, sources, nonclaims, and model realizations.','P026','800-816; 1452-1478','','BirdInt; finite audited interaction calculus','It is not a category, algebra, or closure operator. The body’s 19-field declaration controls an inconsistent 16-field appendix shorthand.'),
('directed cell','canonical','A typed judgment `P_i ← P_j` in which actor `P_i` consumes informant witness data from `P_j` through a typed update under package, profile, visibility, threshold, defect, and audit records.','P026','1538-1600','','cell action','Pair order matters; a cell action does not make the unordered pair observable real.'),
('pair observable','canonical','A separate unordered-pair judgment with joint source-of-truth and branch-compatibility obligations.','P026','1626-1666','','pair record','A real/action cell does not imply a real pair observable; fallback/proxy sources are at most provisional unless explicitly upgraded.'),
('promotion bridge','canonical','A finite typed bridge from a source package to a target package, classified only after required gates and audit records are present.','P026','1670-1745','','promotion','Strict bridge data is separate from target closure and drive.'),
('status family','canonical','A typed classifier codomain tied to one judgment family; BirdInt keeps Role, Cell, Pair, Promotion, Claim, Gate, and Square statuses separate.','P026','180-194; 1518-1666','','status','Status values cannot be transported between families by name resemblance.'),
('access quotient','canonical','The coarsest quotient carrying the observations declared by an instrument/interface.','P028','714','thm:F10','observable quotient','Layer claims must factor through the access quotient unless extra apparatus is declared.'),
('adequacy / no-overread','canonical law','An exact current-layer claim must be constant on access fibers and therefore factor through the access quotient.','P028','839','thm:F11','adequacy','A true carrier fact may still be inadmissible as a current-layer claim.'),
('no-free-distinction','canonical law','A strict visible distinction cannot be produced from the existing access quotient alone; additional memory, bridge, residual budget, scope, or calibration data must be declared.','P028','952','thm:F12','anti-smuggling','This is adjacent to, but does not yet settle, a VII no-free-access theorem.'),
('descent obstruction','canonical','The split-pair set of lower-equivalent points whose transported/readout values disagree; emptiness is equivalent to descent.','P028','2307','thm:F2','split-pair obstruction','Canonical repairs are source refinement or minimal target coarsening.'),
('common quotient / objectivity','canonical law','A public quotient universal across declared access quotients; objectivity means a readout is common across accesses and determined by that public quotient.','P028','3676','thm:F17','public quotient','Common source and common quotient are not the same as common access or a strict join.'),
('common refinement / unification','canonical law','A theory/package refining multiple lower packages under declared bridge conditions.','P028','F51','','unification','A common refinement is not automatically an interaction, strict join, or shared-access certificate.'),
('lawhood descent','canonical law','A candidate law is lawful at a layer exactly when it factors through the available access quotient.','P028','3893','thm:F18','layer lawfulness','Application of a named law still requires a bridge from application objects to theorem objects.'),
('record','canonical','A typed, source-located, auditable association between events/claims and provenance; F20 supplies formed-record discipline.','P028','F20','','event record','Passive logs and unowned analyst annotations need not be formed records.'),
('repair join','canonical endogenous definition','For quotients on a common carrier, the coarsest quotient refining both. It supplies distinctions but not source, cost, utility, access, or interaction admissibility.','P030','458-467','','quotient join','Do not confuse this vertical/common-carrier operation with the desired VII join between formed theories.'),
('predictive surplus','canonical endogenous definition','Declared reduction in closure deficit from current quotient to predictive baseline, or a certified residual surrogate.','P030','471-488','','surplus','Relative to declared futures; not intrinsic hidden meaning, intelligence, or fitness.'),
('carried record / instrument','canonical endogenous definition','A carrier coordinate updated on-kernel whose accepted source is generated by the system trajectory; a carried instrument satisfies the same condition for visibility, thresholds, and checks.','P030','492-508','','internalized record','Physical location inside a boundary is insufficient for carriedness.'),
('E-system','canonical endogenous definition','A formed package plus carried instrument, carried ledger, and carried P1–P5 repair generator, with lawful occurrence separately requiring permission, ledger membership, admissibility, on-kernel realization, and re-audit.','P030','512-528','','endogenous closure system','An organism or agent is not thereby an E-system; P6 is governance, not a repair payload.'),
('closed-loop scope','canonical endogenous definition','A challenge history with complete audit inventory in which every repair occurrence is carried; external repair makes the history subsidized rather than self-repairing.','P030','532-546','','self-repair scope','Choosing a larger carrier may change the verdict and must be declared.'),
('probe economy','canonical endogenous definition','A finite probe catalog, carried active family, exposure budget, and allocation/acquisition/retirement moves; acquisition is strict only against same-family saturation.','P030','550-564','','exposure economy','Exposure is not free and selection is not licensed as an unqualified argmax.'),
('currency','canonical cross-paper notion','A low-dimensional carried quantity with a declared constraint, ledger, potential, or shadow-price role.','P030','350-357','','budget; price','Correlation with outcomes makes a proxy, not a currency.'),
('adequacy residual','canonical','A positive-semidefinite leftover measuring what a dissolving/target probe family sees beyond a native family under a declared audit energy.','P004','436-628','definition/theorems','blind-spot currency','Residuals are interface- and bridge-relative; exact adequacy is not generic.'),
('needle','canonical family notion','A localized obstruction or unresolved direction that survives the currently admitted probe family/budget.','P009','975','','blind spot','Dissolution is framework-bound; not every obstruction is removable by ascent.'),
('dynamic/run-level law','canonical','A law whose statement quantifies over histories, horizons, moving covers, accumulated budgets, adversaries, or transport through time, rather than only static package structure.','P029','catalog introduction','','G-law','G-laws must not be collapsed into static F-laws by dropping temporal hypotheses.'),
('bootstrap obstruction','wishlist-provisional','A dependency cycle in which every rule capable of extending access or enabling a capability requires a premise available only after that extension/capability has already occurred.','WISHLIST','various','','self-bootstrap failure','Not yet a canonical SBT theorem in the supplied corpus; Step 3 must decide its exact carrier and fixed-point form.'),
('expressible / present / reachable / occurrent','wishlist-provisional','Four distinct statuses: stateable in the vocabulary; mechanism instantiated; attainable by a lawful path; observed within a declared horizon.','WISHLIST_from_mm_arc','107-148','','possibility ladder','Existing SBT status machinery motivates this split but does not yet supply this exact four-way VII theorem.'),
('join between theories','wishlist-provisional','A proposed audited contact event/object between independently formed theory packages, with shared evaluation domain, source/provenance, compatibility, and an irreducibility or anti-product witness.','WISHLIST','132-185','','interaction join','Must not be identified by fiat with repair join, categorical product, common refinement, common source, or message exchange.'),
('enablement','wishlist-provisional','A proposed relation in which one package/event makes another formation reachable without necessarily causing, containing, determining, or descending to it.','WISHLIST_foundations_vii_manager','159-173','','birth enablement','Must be typed against causation, descent, sufficiency, and theorist/carrier/co-trigger attribution.'),
]
headers=['term','status','definition','source_paper','source_line','source_label','aliases','noncollapse']
with (SYN/'canonical_glossary.csv').open('w',newline='',encoding='utf-8') as f:
 w=csv.writer(f); w.writerow(headers); w.writerows(terms)
md=['# Canonical SBT glossary and VII provisional vocabulary','',
'Preferred terms are controlled by the deepest explicit definitions in Foundations II–VI. Rows marked `wishlist-provisional` are not silently promoted to established SBT vocabulary.','']
for term,status,definition,paper,line,label,aliases,noncollapse in terms:
 md += [f'## {term}',f'**Status:** {status}.  ',definition,'',f'- **Source:** {paper}, lines/section `{line}`'+(f', `{label}`' if label else '')+'.',f'- **Aliases/history:** {aliases or "—"}.',f'- **Do not collapse:** {noncollapse}','']
(SYN/'CANONICAL_GLOSSARY.md').write_text('\n'.join(md),encoding='utf-8')

aliases=[
('P1','Foundations I: operator rewrite','historical operational realization','P031','1175','Use the Foundations II descent-compatibility meaning as canonical.'),
('P2','Foundations I: gating / constraints','historical operational realization','P031','1181','Use macro-specification representability as canonical; gating is an instance.'),
('P3','Foundations I: autonomous protocol holonomy','historical operational realization','P031','1187','Use enriched route/coherence mismatch as canonical; holonomy is an instance and not arrow.'),
('P4','Foundations I: sectors / invariants','historical operational realization','P031','1195','Use stage/order/transition/refinement as canonical; sectors are an instance.'),
('P5','Foundations I: packaging','compatible shorthand','P031','1201','Use quotient packaging/quotienting; generic path or derivation is excluded.'),
('P6','Foundations I: accounting / audit','compatible shorthand','P031','1207','Use audit/bookkeeping/provenance/replay/checkability; reserve P6_drive for arrow.'),
('join','Foundations V repair join','distinct established operation','P030','458-467','Coarsest common refinement of quotients on one carrier; not yet a theory-interaction join.'),
('interaction','Foundations III directed cell/pair observables','existing intra-calculus notion','P026','1538-1666','VII horizontal theory interaction must be expressed through, not substituted for, BirdInt.'),
('closure','fixed point / idempotent packaging','canonical core','P031','350-590','Do not use as synonym for strictness, endogeny, or completeness of reality.'),
('top-down','structural downward path','restricted existing notion','P026','1790ff','A structural path is not an accepted causal channel without interventions, controls, and registered effect.'),
]
with (SYN/'symbol_alias_ledger.csv').open('w',newline='',encoding='utf-8') as f:
 w=csv.writer(f); w.writerow(['preferred_term','alias_or_older_usage','relation','source_paper','source_line','ruling']); w.writerows(aliases)

corrections=[
('C001','P1–P6 authority','Foundations I uses concrete operational labels; Foundations II explicitly fixes role meanings for the later chain.','Use Foundations II definitions; retain Foundations I labels only as historical realizations.','P031 L1175–1207; P027 L254–303','CLOSED'),
('C002','P3 versus directionality','Some early/application prose places holonomy near arrow language.','P3 route/coherence mismatch is not directionality; require a P6_drive audit and respect protocol-trap/DPI no-gos.','P027 L275–302; P032 NG_ARROW_DPI/NG_PROTOCOL_TRAP','CLOSED'),
('C003','BirdInt tuple arity','P026 body declares 19 components; Appendix A calls a reduced tuple sixteen-component and omits Vis, Source, Real.','Treat the body declaration at L806–814 and internal/model split at L1472–1478 as controlling. Preserve appendix form as legacy shorthand; do not infer 16-field completeness.','P026 L800–816; L1452–1478; L6961–6969','OPEN_SOURCE_INCONSISTENCY_WITH_RULING'),
('C004','Exact-six scope','The phrase exact-six is easy to read as universal algebra or simultaneous activation.','Keep FATCD scope, recognition hypothesis, existential/non-unique decomposition, inactive-channel statuses, and all global nonclaims.','P027 L638–654; L1419; L2715–3030','CLOSED'),
('C005','F-law count and numbering','Foundations IV spans F2–F53 but uses split identifiers and gaps.','Preserve original IDs: 52 rows total, including F13a/b and F15a/b, with no renumbering.','P028 catalog','CLOSED'),
('C006','P040/P058 naming/version','Filenames and internal titles are crossed; texts are near-duplicate but not identical.','Treat as one unresolved version family; cite by stable paper ID and source hash until authorial canonicalization.','P040/P058','OPEN_VERSION_CHOICE'),
('C007','Source extraction and package limits','P020 contains malformed verbatim markup that defeats standard converters; P039 is only a root stub whose 18 declared input files are absent from the supplied archive.','P020 plain text is rebuilt with the conservative repository TeX stripper while TeX remains authoritative. P039 is explicitly blocked for full-text reading and is represented only by its root abstract, declarations, and include map until complete source is supplied.','P020/P039','CLOSED_WITH_RECORDED_SOURCE_BLOCK'),
]
with (SYN/'correction_ambiguity_ledger.csv').open('w',newline='',encoding='utf-8') as f:
 w=csv.writer(f); w.writerow(['id','topic','issue','ruling','sources','status']); w.writerows(corrections)

# ADRs
(DEC/'ADR-0001-canonical-primitive-role-authority.md').write_text('''# ADR-0001 — Canonical authority for P1–P6\n\n**Status:** accepted for Step 1.\n\nFoundations II explicitly fixes the six role meanings for its theorem chain. Therefore its definitions govern the repository. Foundations I’s labels are preserved as concrete operational realizations, not averaged into competing definitions. This prevents generic semantics→P1, generic transitions→P3, and generic paths→P5 misclassification. Directionality uses the narrower P6_drive face and cannot be inferred from P3 holonomy alone.\n\nSources: P027 lines 254–303 and 1208–1245; P031 lines 1175–1207.\n''',encoding='utf-8')
(DEC/'ADR-0002-birdint-domain-tuple.md').write_text('''# ADR-0002 — BirdInt domain tuple arity\n\n**Status:** accepted working ruling; source inconsistency remains recorded.\n\nThe controlling declaration is the body’s 19-component tuple at P026 lines 806–814, reinforced by the internal/model split at lines 1472–1478. Appendix A’s “sixteen-component” record omits `Vis`, `Source`, and `Real`; it is treated as a legacy/reduced presentation, not as the complete domain. No source text is altered. Step 2 should preserve both locations in the claim dossier and, if the paper is revised, request an explicit correction.\n''',encoding='utf-8')
(DEC/'ADR-0003-law-identifier-preservation.md').write_text('''# ADR-0003 — Preserve original law identifiers\n\n**Status:** accepted.\n\nThe F/E/G/no-go registries retain the source identifiers exactly. Foundations IV contains 52 rows from F2 through F53 with split labels F13a/F13b and F15a/F15b and identifier gaps. The repository does not normalize these into F1–F52 because that would break provenance and cross-paper citations.\n''',encoding='utf-8')
(DEC/'ADR-0004-P040-P058-version-family.md').write_text('''# ADR-0004 — P040/P058 version-family handling\n\n**Status:** unresolved canonical choice; controlled handling accepted.\n\nP040 and P058 have normalized five-word-shingle Jaccard similarity 0.687845 and share the SAU theorem stack, examples, and architecture. Their filenames and internal titles are crossed, and the texts contain substantive editorial and theorem-presentation deltas. Neither is silently discarded. They are represented as one version family with two stable IDs and hashes; downstream synthesis cites the shared result family only when both support it and records variant-specific wording separately.\n''',encoding='utf-8')
print(f'roles={len(roles)} glossary={len(terms)} aliases={len(aliases)} corrections={len(corrections)}')
