import FoundationsVII.Enablement.Attribution
import FoundationsVII.Enablement.Endogenous
import FoundationsVII.Enablement.Birth
import FoundationsVII.Enablement.Separation
import FoundationsVII.Enablement.Composition
